### ISSUE TITLE
Gitlab is not good any more?

### ISSUE THREAD

**Issue by KhaledElAnsari** [Rich-Harris/buble#1]

**Comment by Rich-Harris** [comment]
No. I've been meaning to move this (and all my other projects) over for some time. I had high hopes that GitLab could be meaningful competition to GitHub, but it's just not professional-grade. Am going to do a sweep of issues on the old repo, then shut it down and redirect everyone here.

**Comment by trusktr** [comment]
GitHub has many more users, so having it here will help get Buble more traction; that's most important.
