### ISSUE TITLE
Invalid output for async arrow function (expression)

### ISSUE THREAD

**Issue by adrianheine** [Rich-Harris/buble#109]
```js
async (a) => {}
```
is transpiled to
```js
!functionasync (a) {}
```

However,
```js
const x = async (a) => {}
```
is also wrong:
```js
var x = function async (a) {}
```

**Comment by van-nguyen** [comment]
This happens because async is not supported? Please see https://github.com/Rich-Harris/buble/pull/125 I have made a pull request to support this based on #12

**Comment by adrianheine** [comment]
No, that's not true. bublé cannot transpile `async`, but it should already be able to correctly pass it through.

**Comment by van-nguyen** [comment]
Okay I get what you’re saying. In this case, can you please give examples of expected output? Would buble transpile partially leaving async intact syntactically? Or whenever there’s async code it would completely ignore it?

**Comment by aleclarson** [comment]
@van-nguyen It should transpile the arrow function, yet preserve the `async` keyword.

**Comment by adrianheine** [comment]
Related: `async a => {}` makes bublé hang.
