### ISSUE TITLE
Set, Weakset, Map objects not transpiled

### ISSUE THREAD

**Issue by AbhijithNayak** [Rich-Harris/buble#118]
The transpiler at [buble.surge.sh](https://buble.surge.sh/) OR the one installed via npm do not transpile Set, Map, Weakset objects - Is this related to for...of loops not being supported?

**Comment by Rich-Harris** [comment]
Set and Map etc are features of the *environment*, not the *language* - for those you need a polyfill, not a transpiler

**Comment by adrianheine** [comment]
However, bublé indeed does not support iteration (for-of and spread) of the new container types. That's a limitation.
