### ISSUE TITLE
[idea] transpaling on the fly in the browser 💡

### ISSUE THREAD

**Issue by TryHardNinja** [Rich-Harris/buble#133]
Dear Rich Harris
Is it possible to implement transpaling on the fly in the browser?
The idea is that only those features that are not supported in the browser are converted. Sorry for my English
If there are prototypes or ready-made implementations of this idea, I will be glad to see

**Comment by fskreuz** [comment]
Transpilation isn't the same as polyfilling/shimming, where you only add in what you need for a target environment. A transpiler has to parse and transpile. This means pushing the parser, the transpiler, and all their dependencies down the wire. And even if you don't transpile certain pieces of code, you still need to parse the entire code for the transpiler to understand it. You now have a bandwidth and processing problem.

**Comment by trusktr** [comment]
@adrianheine What's the answer? You closed this but an answer wasn't provided.

**Comment by adrianheine** [comment]
Indeed, huh. I think this is out-of-scope for bublé and not a terribly good idea to begin with, but of course everyone is free to work on this as a separate project and I'd be interested to see the results and happy to help from bublé's side.
