### ISSUE TITLE
is preserving parens really necessary?

### ISSUE THREAD

**Issue by aleclarson** [Rich-Harris/buble#136]
https://github.com/Rich-Harris/buble/blob/master/src/index.js#L61

I'm curious why `preserveParens: true` is used when parsing.

It seems nothing in Bublé relies on it. The only paren-aware file is `src/program/types/AssignmentExpression.js`, which simply [skips over](https://github.com/Rich-Harris/buble/blob/master/src/program/types/AssignmentExpression.js#L70) or [removes](https://github.com/Rich-Harris/buble/blob/master/src/program/types/AssignmentExpression.js#L92) the parens.

**Comment by adrianheine** [comment]
I didn't investigate, but removing it breaks some tests, and not all of them because of style issues. If you want to have a closer look and make this work, feel free :)
