### ISSUE TITLE
cherow

### ISSUE THREAD

**Issue by aleclarson** [Rich-Harris/buble#138]
Have you considered switching to [Cherow](https://github.com/cherow/cherow) for the parser?

It's [much faster](https://cherow.github.io/cherow/performance) than acorn.

**Comment by adrianheine** [comment]
I haven't considered that and I am not planning to put any work into it. If someone else does the necessary work and it shows substantial advantages I might merge the change. Note that I am a contributor to acorn, so acorn already has the advantage of me knowing it quite well :)
