### ISSUE TITLE
Determining if the JavaScript API is working

### ISSUE THREAD

**Issue by blachawk** [Rich-Harris/buble#141]
I have successfully gone through [the basics](https://buble.surge.sh/guide/#what-is-buble) of Buble and see my results.  But when I attempt to use the JavaScript API, and use the following code for example:

```
var buble = require( 'buble' );

var input = 'const answer = () => 42;';
var output = buble.transform( input );

console.log( output.code );
console.log( output.map );

```

and click save, nothing happens. Is something suppose to happen? 

Also, when I run from the following node command from the terminal...

`node my-file.js`

node tells me...

`Error: Cannot find module 'buble'`

I installed Buble as an npm global dependency, so I don;t understand why node can't find it and also not sure what next steps should be for processing with the API.

Thanks for any guidance in this

**Comment by friday** [comment]
Since "Click save" and global NPM installation are not Bublé features you're in the wrong place.

**Comment by adrianheine** [comment]
Learning how to use npm and nodejs (which we all had to do once, so don't feel bad about it!) is out of scope here.
