### ISSUE TITLE
converting import to require?

### ISSUE THREAD

**Issue by exebook** [Rich-Harris/buble#143]
Not sure this is the right place to ask I do not even know if I request a feature or advice or something else.

I am using my own bundler, about 250 lines of code, it relies on Babel for now, and I want to switch to Buble because it is faster and less bloated. But I need to convert `import` to `require` in my source files. For some reason you do not support it, I must admit I read the corresponding paragraph in the docs, but did not really get it. Why you do not support it, and how can I get my `require`s easily without relying on another bundler?

I was thinking to write my own convertor for that, should be about 100 lines of code, but to do it right I also need parser, otherwise looking for `\nimport` is not very nice. But probably the way to go if there is no better solution. 

What do you think?

Thank you very much for your great work.

**Comment by fskreuz** [comment]
Why it's not supported and alternatives are explained in the docs over here https://buble.surge.sh/guide/#using-es-modules . Also, it is not mentioned on that page, but you can also use the TypeScript compiler (set `allowJS` to `true`, `target` to ES5, and `module` to UMD) to have it transpile ES6+ back to ES5 _and_ convert the module format.

**Comment by friday** [comment]
TypeScript is a good suggestion. [Sucrase](https://github.com/alangpierce/sucrase) optionally transforms ES Modules to CommonJS as well.

**Comment by damusix** [comment]
In case you're not, I'd like to make you aware of reify https://github.com/benjamn/reify
