### ISSUE TITLE
IE11 does not support const in for..in

### ISSUE THREAD

**Issue by tschaub** [Rich-Harris/buble#144]
Unfortunately, IE 11 does not support `const` (or `let`) in `for..in` loops (see 
 the [kangax compat table](http://kangax.github.io/compat-table/es6/#test-const_for-in_loop_iteration_scope)).  With buble, `const` is not transformed to `var` for `--target ie:11`.  So this kind of code breaks:
```
$ echo 'for (const foo in bar) {}' > input.js
$ npx buble input.js --target ie:11
for (const foo in bar) {}
```

The most conservative change would be to flip the `letConst` bit for IE 11.  For example:
```diff
diff --git a/src/support.js b/src/support.js
index 2183032..7076329 100644
--- a/src/support.js
+++ b/src/support.js
@@ -46,7 +46,7 @@ export const matrix = {
                     8: 0b00000000000000000000,
                     9: 0b01000000000000000000,
                    10: 0b01000000000000000000,
-                   11: 0b01000000000100000000
+                   11: 0b01000000000000000000 // no let/const in for loops
        },
        edge: {
                    12: 0b01001010100101001101,
```

I'd be happy to propose a PR if this or another solution would be accepted.

**Comment by adrianheine** [comment]
Yes, please prepare a patch for this!

**Comment by tschaub** [comment]
@adrianheine see #154 for the PR.
