### ISSUE TITLE
.babelrc support?

### ISSUE THREAD

**Issue by strarsis** [Rich-Harris/buble#145]
I want to add support for dynamic import syntax using this `,babelrc`:
```json
{
  "plugins": ["syntax-dynamic-import"]
}
````
However, it seems to be ignored.

`buble` is used with webpack (roots.io [sage9](https://github.com/roots/sage) theme).
```js
// ...
      {
        test: /\.js$/,
        exclude: [/node_modules(?![/|\\](bootstrap|foundation-sites))/],
        use: [
          { loader: 'cache' },
          { loader: 'buble', options: { objectAssign: 'Object.assign' } },
        ],
      },
// ...
````

This issue may be related: https://github.com/babel/babel-loader/issues/552

```js
{ loader: 'buble', options: { objectAssign: 'Object.assign', babelrc: true } },
````
doesn't work either.

**Comment by fskreuz** [comment]
I'm not sure what you're trying to do. While Babel and Buble are both ESNext-to-ESNow transpilers, they are totally different implementations. Buble doesn't consume Babel configuration or plugins at all.

If you meant imlementing an `rc` file for Buble (i.e. have it scan for a `.bublerc` if no config is passed), that would totally be possible. However, it will still be incompatible with `.babelrc` for the said reason above.

**Comment by strarsis** [comment]
@fskreuz: Thanks. So for this particular project I would have to switch to Babel for supporting this feature (`syntax-dynamic-import`).
