### ISSUE TITLE
'return' outside of function

### ISSUE THREAD

**Issue by KutnerUri** [Rich-Harris/buble#147]
I am working on a live preview application, and I am using bublé to transform jsx into js.

However I am getting exceptions on having 'return' not in a function scope.
I realize this is happening because of acorn, it doesn't have the flag **allowReturnOutsideFunction** turned on.

Solution:
Option (1) - manually wrap all code with "`(function() {`" and  "`})()`" before passing it through bablé. This doesn't completely solve the issue and adds another layer in the stack.
Option (2) - allow passing options to acorn, which follows inversion of control but add more configuration.
Option (3) - **add hardcoded `allowReturnOutsideFunction: true` to the acorn parser config inside of Bublé**.

Option 3 seems to be the best since bublé is just a transpiler, not a linter, and the return statement doesn't bother it otherwise.

**Comment by adrianheine** [comment]
I'm okay with option 3, could you open a pull request?

**Comment by KutnerUri** [comment]
--> #155

**Comment by adrianheine** [comment]
Fixed with #155.
