### ISSUE TITLE
Body-less loop emits unusual code

### ISSUE THREAD

**Issue by jbmonroe** [Rich-Harris/buble#148]
`while (!spc(str[end--]));`

becomes

`while (!spc(str[end--])){ ; }`

JSHint flags it.  I know better than to use JSLint.

Anyway, the code runs, but it pegs the weirdometer, since it seems to be asserting a style mandate rather than downshifting from ES6 to ES5.  Side effect of genning from the AST?

**Comment by fskreuz** [comment]
Buble doesn't generate code from an AST. It, instead, does string manipulation by adding to/moving around/removing from the original code. It's highly likely that Buble is adding the `{` and `}` to explicitly set the block, but didn't touch the block body (where the only thing inside it is the `;`).

**Comment by goto-bus-stop** [comment]
This was done to avoid the problem mentioned in https://gitlab.com/Rich-Harris/buble/issues/110. A transformation of a loop body can cause a single statement to become multiple statements, so the {} may be required.

**Comment by adrianheine** [comment]
It would probably be possible to detect some of these cases.

**Comment by jbmonroe** [comment]
I suppose the logical question to ask is whether it makes a difference at run-time.  If not, there's no point in fixing it.  The interpreter could easily be smart enough to work around it.

**Comment by adrianheine** [comment]
There's no difference at run-time. Both scripts are parsed into equivalent ASTs and the interpreter doesn't even know about these syntactical differences.

**Comment by jbmonroe** [comment]
If all it does is freak out linters, then I'm tempted to withdraw this.
