### ISSUE TITLE
Pure annotation for class tree-shaking

### ISSUE THREAD

**Issue by bisubus** [Rich-Harris/buble#156]
Inherited classes are transpiled to IIFE:

```
var Circle = (function (Shape) {
  function Circle () {
    Shape.apply(this, arguments);
  }if ( Shape ) Circle.__proto__ = Shape;
  Circle.prototype = Object.create( Shape && Shape.prototype );
  Circle.prototype.constructor = Circle;
  return Circle;
}(Shape));
```
IIFEs are considered side-effects, this prevents them from being dropped by a minifier when a class is unused.

This problem has been addressed in babel/babel#5632, the solution is to add `/*@__PURE__*/` comment annotation to transpiled class IIFE, so it could be properly interpreted by minifiers, namely UglifyJS and Terser:
```
var Circle = /*@__PURE__*/(function (Shape) {
/* ... */
}(Shape));
```

**Comment by adrianheine** [comment]
I'd happily accept a pull request for this!
