### ISSUE TITLE
Where does Buble store cache?

### ISSUE THREAD

**Issue by matthew-dean** [Rich-Harris/buble#158]
I'm hitting an issue where a dependency's dependency is Buble, which is failing. Basically when downgrading the dependency, Buble seems to be using a previously converted module. Wiping the projects `node_modules/` and `package-lock.json` file has no effect. And then restoring the original dependency version doesn't fix it either. Once Buble starts erroring out, it continues to error out. We get errors like:

```
./node_modules/buble/dist/buble-browser.es.js
10283:15-21 'acorn' does not contain an export named 'Parser'.
./node_modules/buble/dist/buble-browser.es.js
263:9-19 "export 'default' (imported as 'require$$0') was not found in 'acorn'
./node_modules/buble/dist/buble-browser.es.js
264:17-27 "export 'default' (imported as 'require$$0') was not found in 'acorn'
```
The dependencies definitely have the listed exports, but once these errors start, we can't seem to eliminate them. Buble insists any updated modules don't have the exports listed.

How do we reset Buble too a "clean" state? It doesn't seem to re-compile files no matter if you try to delete any installed packages anywhere.

**Comment by matthew-dean** [comment]
Oh, it looks like this was caused by `react-styleguidist` having a `^0.19.3` dependency, which failed when Buble was bumped to 0.19.5.

**Comment by adrianheine** [comment]
Closing this in favor of #159.
