### ISSUE TITLE
[bug] Edge 12 or 13 targets don't transpile destructuring.

### ISSUE THREAD

**Issue by trusktr** [Rich-Harris/buble#16]
According to MDN, destructuring is supported on Edge 14+, but setting the target to edge:12 or edge:13 doesn't transpile the following:

```js
this._elementManager.setClasses(...properties.classes);
```

I was expecting it to use `Function.prototype.apply`.

**Comment by trusktr** [comment]
If MDN is true, then here's a PR: https://github.com/Rich-Harris/buble/pull/17

**Comment by adrianheine** [comment]
That's actually a spread operator applied to an array in a function call, which [is supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) in Edge 12.

**Comment by trusktr** [comment]
Ah, confusing. I feel like the MDN docs could unify restructuring and spread features in a better way. It's hard to know exactly what to search for.
