### ISSUE TITLE
Significant bundle growth between 0.19.4 and 0.19.6

### ISSUE THREAD

**Issue by sapegin** [Rich-Harris/buble#171]
After upgrading my webpack bundle size has increased by ~300 KB, Buble version is the only difference.

Buble 0.19.4:

![image 2018-11-20 at 4 08 18 pm](https://user-images.githubusercontent.com/70067/48782452-8569d300-ecde-11e8-83e4-7813fc09e2cd.png)

Buble 0.19.6:

![image 2018-11-20 at 4 08 59 pm](https://user-images.githubusercontent.com/70067/48782493-9b779380-ecde-11e8-8791-ed3982331feb.png)

[Webpack stats for 0.19.4](http://wow.sapegin.me/78ada8ea682a). [Webpack stats for 0.19.6](http://wow.sapegin.me/67c4f6431e2b)

**Comment by adrianheine** [comment]
Yeah, I know, sorry. See #165 for the fix and #159 for the back-story.

**Comment by adrianheine** [comment]
Fixed in #165 (still needs a release, though).

**Comment by kopax** [comment]
Hi, can we release this? It seems that it affects others projects https://github.com/styleguidist/react-styleguidist/issues/1310#issuecomment-471142372

**Comment by adrianheine** [comment]
How does the issue you linked relate to this?

**Comment by kopax** [comment]
Apparently not at all.

**Comment by adrianheine** [comment]
Just released v0.19.7.
