### ISSUE TITLE
Spread operator in combination with a set is incorrectly transpiled

### ISSUE THREAD

**Issue by flekschas** [Rich-Harris/buble#173]
The following statement...

```javascript
console.log([...new Set([1,2,2])]);
// => [1, 2]
```

...is unfortunately transpiled by Buble the code into:

```javascript
console.log([].concat( new Set([1,2,3]) ));
// => [Set(3)]
```

But the statements are functionally not equivalent. I would expect Buble to either handle the spread operator correctly or throw a warning or error.

This is potentially related to #81

**Comment by adrianheine** [comment]
This topic has been discussed somewhat in #81.

**Comment by adrianheine** [comment]
Closing this in favor of #131.
