### ISSUE TITLE
[BUG] Classes are compiled to put `this` before `super()` calls.

### ISSUE THREAD

**Issue by trusktr** [Rich-Harris/buble#18]
I added my own support number based on `ie:10`, so it looks like this:

```js
		    10: 0b1000000000000000000000000000010,
```

I wanted to leave classes alone, to compile those with Babel afterword.

It turns out, Buble is modifying the classes, and putting `this` before `super()` which turns into an error in Babel because `this` isn't allowed to be used before `super()`. The output look like this:

```js
        constructor (options) {
            var this$1 = this;
            if ( options === void 0 ) options = {};

            super(options);

            // use options
        }
```

Oddly, `this$1` is never used for anything. Not sure why Buble would put that there.

**Comment by trusktr** [comment]
I'm using rollup-plugin-buble. Could it be a problem there?

**Comment by adrianheine** [comment]
Can you give an example? I couldn't reproduce the issue.

**Comment by trusktr** [comment]
Dang, I should've forked my repo and posted it. Will do next time. I may get around to it while testing builds for browsers before next release of my project.

**Comment by adrianheine** [comment]
Please feel free to reopen if you see the issue again.
