### ISSUE TITLE
Object initializer get/set accessor shorthand is not transpiled, breaks old browsers.

### ISSUE THREAD

**Issue by trusktr** [Rich-Harris/buble#20]
F.e., even with `--target ie:8`, 

```js
let o = { get foo() {return 1} }
```

is compiled to

```js
var o = { get foo() {return 1} }
```

IE 11 throws the infamous "Expected object" error.

**Comment by trusktr** [comment]
As a workaround, I'll process this with a post-buble babel step.

**Comment by trusktr** [comment]
Actually, despite Buble having this bug, this output is appearing in module export code (after transpile), which Rollup handles.

If I downgrade from Rollup 0.50.0 to 0.45.2, the problem goes away! I'll make a new issue in Rollup.

**Comment by trusktr** [comment]
~If I downgrade from Rollup 0.50.0 to 0.45.2, the problem goes away! I'll make a new issue in Rollup.~

**Comment by trusktr** [comment]
Here's the related issue in Rollup: https://github.com/rollup/rollup/issues/1671

**Comment by nathancahill** [comment]
Is IE 11 a typo in this issue? Getters are supported since IE 9: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Browser_compatibility

**Comment by trusktr** [comment]
It was a mistake, the other issue is closed. Closing this one too.

**Comment by adrianheine** [comment]
Babel doesn't handle this either, btw.
