### ISSUE TITLE
Which acorn-object-spread?

### ISSUE THREAD

**Issue by SnarkBoojum** [Rich-Harris/buble#26]
Hi,

I'm trying to package bublé in Debian, but I'm hitting a problem with acorn-object-spread : there's UXtemple's one, which is outdated. There is Adrian Heine's [acorn5-object-spread](https://github.com/adrianheine/acorn5-object-spread), which is more up to date. And finally, you seem to have your own fork.

What am I supposed to do?

**Comment by adrianheine** [comment]
If you are considering switching to my fork, take a look at #25. Rich-Harris/acorn-object-spread is UXtemple's version with UXtemple/acorn-object-spread#3 merged, which makes it not completely broken with acorn >= 4, but still has some bugs in edge cases I fixed.

**Comment by SnarkBoojum** [comment]
Or perhaps you could all cooperate on a single repository?

**Comment by adrianheine** [comment]
Sure, I'm not keen on having my fork as soon as somebody steps up and becomes a responsive maintainer :)

**Comment by SnarkBoojum** [comment]
Ok, now buble uses acorn5-object-spread : I'll package it.

When will there be a release of buble with that change?

Thanks!
