### ISSUE TITLE
[!] (buble plugin) TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by leeoniya** [Rich-Harris/buble#37]
this is a regression with bundling CodeMirror from v0.16.0 -> v0.17.0

![rollup-foo](https://user-images.githubusercontent.com/43234/32561377-be9d7e7e-c471-11e7-8cad-0c947585b8fb.png)

**Comment by kaisermann** [comment]
I'm currently getting the same error. Although my project was building fine a few days ago 😢

**Comment by adrianheine** [comment]
That's caused by ternjs/acorn#621 afaik.

**Comment by adrianheine** [comment]
Note that CodeMirror currently specifies 0.15.0 as dependency. How did you end up running this version of bublé?

**Comment by leeoniya** [comment]
i have a custom fork of CM and sometimes i get adventureous and `npm update` :)

**Comment by Rich-Harris** [comment]
fixed in 0.18, thanks
