### ISSUE TITLE
Invalid output when returning a object with a computed property key

### ISSUE THREAD

**Issue by blikblum** [Rich-Harris/buble#51]
When a object that uses a computed property key (`{[key]: value}`) is returned in a function, the output is invalid.

Here's an [example](http://buble.surge.sh/#const%20deepifyKeys%20%3D%20(key%2C%20val)%20%3D%3E%20%7B%20%20%20%20%0A%20%20return%20%7B%20%5Bkey%5D%3A%20val%20%7D%0A%7D):

input:
```
const deepifyKeys = (key, val) => {    
  return { [key]: val }
}
```

output:
```
var deepifyKeys = function (key, val) {    
  return ( obj = {}
  var obj;, obj[key] = val, obj )
}
```

A more complex example with the actual code that hit this bug can be found [here](http://buble.surge.sh/#const%20deepifyKeys%20%3D%20(obj)%20%3D%3E%20mapObject(obj%2C%0A%20%20(%5Bkey%2C%20val%5D)%20%3D%3E%20%7B%0A%20%20%20%20const%20dashIndex%20%3D%20key.indexOf('-')%0A%20%20%20%20if%20(dashIndex%20%3E%20-1)%20%7B%0A%20%20%20%20%20%20return%20%7B%0A%20%20%20%20%20%20%20%20%5Bkey.slice(0%2C%20dashIndex)%5D%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%5Bkey.slice(dashIndex%20%2B%201)%5D%3A%20val%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20%7B%20%5Bkey%5D%3A%20val%20%7D%0A%20%20%7D%0A)).

**Comment by blikblum** [comment]
Using the shorthand notation to return the object works. See this [example](http://buble.surge.sh/#const%20deepifyKeys%20%3D%20(key%2C%20val)%20%3D%3E%20(%7B%20%5Bkey%5D%3A%20val%20%7D)%0A).

**Comment by adrianheine** [comment]
This has been fixed with #34, i. e. >=0.17.1.

**Comment by blikblum** [comment]
Using 17.3 here with same problem

**Comment by adrianheine** [comment]
Hm, can you double-check that you are indeed using the right bublé version? On my system, this looks fine:

```shellsession
$ bin/buble --version
Bublé version 0.17.3

$ echo "const deepifyKeys = (key, val) => {
  return { [key]: val }
}" | bin/buble
var deepifyKeys = function (key, val) {    
  return ( obj = {}, obj[key] = val, obj )
  var obj;
}
```

**Comment by adrianheine** [comment]
I see. I think the problem is the nesting of computed properties:

```js
return {
  [key.slice(0, dashIndex)]: {
    [key.slice(dashIndex + 1)]: val
  }
}
```

I'll look into that.

**Comment by blikblum** [comment]
@adrianheine 
Many thanks
