### ISSUE TITLE
scope bug: read-only error

### ISSUE THREAD

**Issue by kzc** [Rich-Harris/buble#59]
```
$ bin/buble -v
Bublé version 0.18.0
```
```js
$ cat scope_bug.js
const bar = "FAIL";
!function() {
    function foo() {
        --bar;
        bar = ["fail", "PASS", "Fail"][bar];
    }
    var bar = 2;
    foo();
    console.log(bar);
}();
```
```js
$ cat scope_bug.js | node
PASS
```
```js
$ cat scope_bug.js | bin/buble 
---
1 : const bar = "FAIL";
2 : !function() {
3 :     function foo() {
4 :         --bar;
            ^^^^^
bar is read-only (4:8)
```
Related sources:

[src/program/types/AssignmentExpression.js#L7-L9](https://github.com/Rich-Harris/buble/blob/v0.18.0/src/program/types/AssignmentExpression.js#L7-L9)
[src/program/types/UpdateExpression.js#L7-L11](https://github.com/Rich-Harris/buble/blob/v0.18.0/src/program/types/UpdateExpression.js#L7-L11)

**Comment by adrianheine** [comment]
My first guess is that we can only improve this by delaying validation of update and assignment expressions till after we traversed the whole tree. A simpler alternative would be to turn this error into a warning.

**Comment by kzc** [comment]
I think the former is the way to go. A warning with false positives is not helpful.

Acorn catches a number of these types of errors doesn't it? If so, maybe this logic is not required at all.

**Comment by adrianheine** [comment]
Well, I think a warning would be a reasonable approach, exactly because it could be a false positive. Also, a) it is easily fixable b) it is confusing for humans, so fixing it makes sense anyway. But I'm not opposed to the more elaborate and correct solution.

As far as I know acorn doesn't do anything like this, for example it parses `const x = 1; ++x`.

**Comment by kzc** [comment]
The problem is that warnings are almost always ignored by users - even if valid. What's the downside of passing illegal code to Buble as you have above? The generated code will incorrectly behave as if the `const` is a `let`?

**Comment by adrianheine** [comment]
Yes, it will be transpiled to a `var`. Since most people never run their untranspiled code, this would effectively mean that they can theoretically use `const` in all kinds of wrong places, ignore the warnings and have incorrect assumptions about their code.

**Comment by kzc** [comment]
That doesn't sound desirable - particularly for users like me who never use linters.

**Comment by adrianheine** [comment]
I actually found an easy solution for this: The checks used to happen in `initialise`, now I moved them to `transpile`. I also added them destructuring assignments.

**Comment by kzc** [comment]
@adrianheine Well done! Thanks.
