### ISSUE TITLE
JSX fragments support

### ISSUE THREAD

**Issue by sapegin** [Rich-Harris/buble#62]
JSX has a [new syntax for fragments](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html):

```jsx
render() {
  return (
    <>
      <ChildA />
      <ChildB />
      <ChildC />
    </>
  );
}
```

Is this something you want to support in Buble?

**Comment by nathancahill** [comment]
Yes, I'd love to see this, as Babel supports it and [Preact is hoping to support it](https://github.com/developit/preact/issues/929#issuecomment-345283184).

**Comment by adrianheine** [comment]
I started working on this, but I think there is a bug in the `acorn-jsx` implementation, see https://github.com/RReverser/acorn-jsx/pull/83#issuecomment-349726310.
