### ISSUE TITLE
Destructured catch parameters are not transpiled

### ISSUE THREAD

**Issue by adrianheine** [Rich-Harris/buble#76]
[Spec](https://tc39.github.io/ecma262/#prod-CatchParameter). Example:
```js
try {} catch ({message}) {}
```

**Comment by nathancahill** [comment]
[Babel's handling](https://github.com/babel/babel/blob/f5ef928586f592aa2d8bb60120ae58833d17e0db/packages/babel-plugin-transform-destructuring/src/index.js#L431). I think we need a CatchClause type in Buble.
