### ISSUE TITLE
TypeError: Cannot read property 'magicString' of undefined

### ISSUE THREAD

**Issue by trusktr** [Rich-Harris/buble#85]
When building with Rollup `0.50.0`, using `rollup-plugin-buble` and `buble` both at `0.16.0`, I get an error like this:

```
[!] TypeError: Cannot read property 'magicString' of undefined
TypeError: Cannot read property 'magicString' of undefined
    at new CompileError (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/buble/src/utils/CompileError.js:8:30)
    at error (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/rollup/dist/rollup.js:185:14)
    at Object.error (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/rollup/dist/rollup.js:9407:6)
    at promise.then.previous (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/rollup/dist/rollup.js:9416:32)
    at <anonymous>
```

The line where it happens is like follows

```js
import locate from './locate.js';
import getSnippet from './getSnippet.js';

export default class CompileError extends Error {
	constructor ( node, message ) {
		super();

		const source = node.program.magicString.original; // RIGHT HERE
		const loc = locate( source, node.start );

		this.name = 'CompileError';
		this.message = message + ` (${loc.line}:${loc.column})`;

		this.stack = new Error().stack.replace( new RegExp( `.+new ${this.name}.+\\n`, 'm' ), '' );

		this.loc = loc;
		this.snippet = getSnippet( source, loc, node.end - node.start );
	}

	toString () {
		return `${this.name}: ${this.message}\n${this.snippet}`;
	}
}
```

So, it looks like I have a compile error, but I can't see what it actually is because the error is not able to be thrown properly.

**Comment by trusktr** [comment]
I made a reproduction here: https://github.com/trusktr/infamous/tree/Rich-Harris-buble-issue-85

To reproduce run `npm i && npm run build-global`.

**Comment by adrianheine** [comment]
Your actual error:

> Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip transformation and disable this error, or `transforms: { dangerousTaggedTemplateString: true }` if you know what you're doing (38:33)

**Comment by adrianheine** [comment]
If you update your bublé dependency you should get the actual error.

**Comment by trusktr** [comment]
Ah, I see, it was just an unhelpful error message. I'll update, and use Babel for that.

**Comment by adrianheine** [comment]
You can definitely use tagged template strings with bublé, it just doesn't provide a `raw` property, which probably most tag functions don't use.

**Comment by trusktr** [comment]
Hehe, funny thing is I'm using the `raw` property to implement [`regexr`](https://www.npmjs.com/package/regexr) which relies on `raw` to make it easy to compose RegExps with template strings without having to double-escape everything.

Yep, after updating the message is much more helpful:

```
[!] (buble plugin) CompileError: Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip transformation and disable this error, or `transforms: { dangerousTaggedTemplateString: true }` if you know what you're doing (11:20)
```

**Comment by trusktr** [comment]
It'd be great if the playground was configurable so we can test out various options. f.e. wish this could work for just taking a look at what it does without having to go install stuff and do it from command line: https://buble.surge.sh/#function%20foo()%20%7B%7D%0Aconst%20f%20%3D%20foo%60asdfasdfasdf%60

**Comment by trusktr** [comment]
Ah, this is nice: https://jsfiddle.net/rwk0qt4f/22 !

**Comment by LeeeeeeM** [comment]
For some users, rollup does not support the syntax (for .... of)
