### ISSUE TITLE
IE10 - TypeError: Object doesn't support property or method 'initialise'

### ISSUE THREAD

**Issue by JakeSidSmith** [Rich-Harris/buble#88]
Hey there,

I'm using [React Styleguidist](https://github.com/styleguidist/react-styleguidist) which uses buble behind the scenes.

It seems that buble is the cause of [this issue](https://github.com/styleguidist/react-styleguidist/issues/375) that was closed a while ago. I believe this only occurs in IE10 (and probably less).

It seems that the cause of the issue is [this line](https://github.com/Rich-Harris/buble/blob/8f4155682bb803f4edb2c932182a0ba3bd7f6096/src/program/Program.js#L31), though I'm not entirely sure how this all works.

It may be due to an error in [this file](https://github.com/Rich-Harris/buble/blob/master/src/program/wrap.js), but I haven't had too long to look into this.

Here's a shot of the minified stacktrace.

<img width="1202" alt="screen shot 2018-01-02 at 22 44 29" src="https://user-images.githubusercontent.com/5850625/34503271-5a385930-f00f-11e7-9613-13d6192d7a96.png">

Additional info: 

```
buble@0.15.2

acorn@3.3.0
acorn-object-spread@1.0.0

react-styleguidist@6.0.30
react-docgen-typescript@1.1.0
```

**Comment by nathancahill** [comment]
Buble@0.15.2 is nearly a year old at this point, have you tried with the latest build (0.18?)

**Comment by JakeSidSmith** [comment]
I will give it a go, but was put off due to [this issue](https://github.com/styleguidist/react-styleguidist/issues/764).

**Comment by JakeSidSmith** [comment]
Actually, ignore that. I'll just give it a go when I have some time, and will close this issue if the newer version solves my problems. :)

**Comment by JakeSidSmith** [comment]
No luck due to this line in [acorn5-object-spread](https://github.com/adrianheine/acorn5-object-spread/blob/master/inject.js#L10). Will fork and fix. 🙂

**Comment by JakeSidSmith** [comment]
@nathancahill have opened a [pull request](https://github.com/adrianheine/acorn5-object-spread/pull/1) that should fix [this issue](https://github.com/styleguidist/react-styleguidist/issues/764), and will hopefully be merged soon. Then I'll be able to re-test.

**Comment by adrianheine** [comment]
Hi, bublé is currently [built to support node 4](/Rich-Harris/buble/blob/master/rollup.config.js#L14). You could add other targets in your own build. I'm currently not interested in removing reasonably old JavaScript syntax from acorn5-object-spread, see also browserify/browserify/pull/1794 for a similar discussion.

**Comment by JakeSidSmith** [comment]
@Rich-Harris apparently acorn `5.4` now supports object spread without plugins: https://github.com/adrianheine/acorn5-object-spread/pull/1#issuecomment-362635815

**Comment by adrianheine** [comment]
I updated the acorn dependency and removed the plugin in ad7f766e88ea64d319ec36f09314cf783ca1d328.

**Comment by happier2** [comment]
@JakeSidSmith I encountered the same problem with styleguidist. Did you fixed this problem?

**Comment by happier2** [comment]
@JakeSidSmith thanks for your reply. maybe, I should give up too...

**Comment by adrianheine** [comment]
I'm closing this for now. I'll happily merge simple changes that improve bublé compatibility for example with IE 10, but I am not actively checking for anything other than node >= 4.
