### ISSUE TITLE
Clarify what environments are targeted by buble's codebase

### ISSUE THREAD

**Issue by Andarist** [Rich-Harris/buble#93]
`react-styleguidist` uses `buble` in the browser, but unfortunately `buble` ships to npm codebase containing some es6 features.

I'd only want to clarify what environments buble is targeting - in which node/browser versions it should run out of the box? Would you consider transpiling more features to support older browsers like IE11 or should we fix this in a tool like `react-styleguidist` by transpiling buble on our own?

**Comment by adrianheine** [comment]
@Rich-Harris what do you think? Since IE11 doesn't support classes, #66 and #40 are relevant here, too. I would say bublé should only be compiled for node 4.

**Comment by Andarist** [comment]
Maybe you could transpile with node4 support in mind for `main` entry and for the `browser` it could be transpiled down to es5? Although Im not sure what to do about `module` entry - at the moment its mainly targeting browsers too (as its understood by bundlers), but maybe some people somehow bundle for node too? 🤔 Would be actually good to have `browser:module`/`module:browser` 😂

**Comment by Andarist** [comment]
@adrianheine WDYT about the proposed solution of transpiling with different targets in mind for `main` and `browser` fields?

**Comment by adrianheine** [comment]
I think that makes sense. We would have to find a workaround for #40, though.

**Comment by Andarist** [comment]
Imho that's a separate issue, that could ofc be fixed/tackled somehow but it is not tightly coupled to this one - or am I missing something?

**Comment by adrianheine** [comment]
It is coupled, because transpiling classes will make our errors not have a `description` or a `stack`, so we would basically break the browser build.

**Comment by Andarist** [comment]
Hm, I can't be sure about all old browser, but you assign custom `stack` property [here](https://github.com/Rich-Harris/buble/blob/5f05fdac659158d0d03c6eff94e97525986b44b2/src/utils/CompileError.js#L18) and it is readable in latest Chrome (when using transpiled version of `CompileError` class). Ain't sure about `description` because I don't know origin of this property - you do not specify it in `CompileError`'s constructor nor it is built-in property of native `Error`. Maybe you had some other prop in mind?

most.js has migrated to transpiled version of buble's output (because they have migrated to babel which didnt support extending built-ins) for their [custom `DisposeAllError`](https://github.com/mostjs/core/pull/143/files#diff-27c227b356759e71e2b822c95cf32715L44) and it seems to work OK.

**Comment by adrianheine** [comment]
Sorry, I meant `message`. It seems like you're right and `CompileError` already does what's necessary, so we should be able to do this.
