### ISSUE TITLE
JSX - Error: Cannot overwrite a zero-length range – use insertLeft or insertRight instead

### ISSUE THREAD

**Issue by alasdairhurst** [Rich-Harris/buble#96]
The following jsx code examples cause a parsing error
```Error: Cannot overwrite a zero-length range – use insertLeft or insertRight instead```
```
	<div className={"foo"}disabled />;
```
```
	<div className="foo"disabled />;
```
Notice the issue is the missing space after the jsx properties. It works fine in babel but causes the error here.

**Comment by adrianheine** [comment]
Which bublé version are you using? Both snippets work fine in my current master.

**Comment by alasdairhurst** [comment]
@adrianheine Yup, looks like an older version - ^0.15.2.

**Comment by adrianheine** [comment]
Ok, I'm closing this for now.
